### ISSUE TITLE
Is this repo downloading the latest stable diffusion v1-4 weights?

### ISSUE THREAD

**Issue by mln-wave** [entrpn/serving-diffusion#1]
Hi,

Thanks for giving the code to deploy to vertex AI serverless.
Is [this line](https://github.com/entrpn/serving-diffusion/blob/75c9c5b15c42e58a6c3143dd11682d7234450bc3/app/load_weights.py#L49) downloading the latest version of stable difusion (v1-4) or any other version?

**Comment by entrpn** [comment]
@mln-wave it downloads the latest, v1-4. You can look at the Dockerfile to verify.

**Comment by mln-wave** [comment]
Hi @entrpn ,
Thanks. Got it.
I want to run in bit low config GPUs, so thinking to use float16 precision to be able to run on 16GB VRAM GPUs. 
In case of `StableDiffusionPipeline` library from Huggingface, we can mention as below to be able to run on 19GB VRAM also. So, what code changes we need to make in this repo for float 16 precision? 

`pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", revision="fp16", torch_dtype=torch.float16, use_auth_token=access_token)  ` 

Thankyou.

**Comment by entrpn** [comment]
I am able to run this model on a GPU with 16GB VRAM, so I don't think you'll have an issue, but if you want to, you can run in half precision by changing [this](https://github.com/entrpn/serving-diffusion/blob/master/app/main.py#L71) line to:

```python
model = load_model_from_config(config, "models/ldm/stable-diffusion-v1/model.ckpt").half()
``` 

Just by running some tests, that reduced memory consumption from around 14 GB to 11 GB.

**Comment by TejaswiniiB** [comment]
ok, will try it. Thankyou!
