### ISSUE TITLE
Getting error while running gcpp_deploy : "400 Error: model server never became ready. Please validate that your model file"

### ISSUE THREAD

**Issue by TejaswiniiB** [entrpn/serving-diffusion#3]
Hi, 
It ran fine and there was last step of gc_deploy, and Im getting the following error. I am using `asia-south1` region, `n1-standard-4` machine, and `NVIDIA_TESLA_T4` accelerator. Can you let me know why I am getting this error during deploying?

```
To use this Endpoint in another session:
endpoint = aiplatform.Endpoint('projects/1027408664936/locations/asia-south1/endpoints/1472078943824642048')
Deploying model to Endpoint : projects/1027408664936/locations/asia-south1/endpoints/1472078943824642048
Deploy Endpoint model backing LRO: projects/1027408664936/locations/asia-south1/endpoints/1472078943824642048/operations/6849460461788725248
Traceback (most recent call last):
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/gcp_deploy.py", line 96, in <module>
    main()
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/gcp_deploy.py", line 86, in main
    model = deploy_model_with_dedicated_resources_sample(model,
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/gcp_deploy.py", line 22, in deploy_model_with_dedicated_resources_sample
    model.deploy(
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/.venv/lib/python3.9/site-packages/google/cloud/aiplatform/models.py", line 3201, in deploy
    return self._deploy(
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/.venv/lib/python3.9/site-packages/google/cloud/aiplatform/base.py", line 793, in wrapper
    return method(*args, **kwargs)
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/.venv/lib/python3.9/site-packages/google/cloud/aiplatform/models.py", line 3376, in _deploy
    endpoint._deploy_call(
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/.venv/lib/python3.9/site-packages/google/cloud/aiplatform/models.py", line 1233, in _deploy_call
    operation_future.result()
  File "/home/Documents/projects/Text_to_Image/gcp_vertex_ai_scalable/serving-diffusion/.venv/lib/python3.9/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.FailedPrecondition: 400 Error: model server never became ready. Please validate that your model file or container configuration are valid. Model server logs can be found at https://console.cloud.google.com/logs/viewer?project=1027408664936&resource=aiplatform.googleapis.com%252FEndpoint&advancedFilter=resource.type%3D%22aiplatform.googleapis.com%2FEndpoint%22%0Aresource.labels.endpoint_id%3D%221472078943824642048%22%0Aresource.labels.location%3D%22asia-south1%22.

```

**Comment by TejaswiniiB** [comment]
T4 wasn't available in asia-south1 region, changed it to asia-southeast-1 region,  It is working fine now, thank you.

**Comment by TejaswiniiB** [comment]
T4 wasn't available in asia-south1 region, changed it to asia-southeast-1 region,  It is working fine now, thank you.

**Comment by prashanaga** [comment]
Hi,
I am also getting same error 
google.api_core.exceptions.FailedPrecondition: 400 Error: model server never became ready. Please validate that your model file or container configuration are valid

I am using machine_type="n1-standard-4"
and region "us-central1"

**Comment by entrpn** [comment]
@prashanaga what's the TPU type you're using? This repo is deprecated, I will note it in the read me, take a look at https://github.com/entrpn/serving-model-cards/tree/main/serving-stable-diffusion

**Comment by prashanaga** [comment]
Hi,

I am not using any TPU, just standard machine

**Comment by entrpn** [comment]
@prashanaga sorry, I meant to write `GPU`, not TPU. This won't run without an accelerator, you'll get those errors because the model is too large for that machine type without a GPU.

**Comment by prashanaga** [comment]
Hi,

I am using just random forest.
Will that too requires GPU?

**Comment by entrpn** [comment]
Ah, for this, it should not require it. In the console, go to the endpoint and there should be a logs link. Look at the logs there and see if there's some other error that is causing this.

**Comment by prashanaga** [comment]
Hi ,

ERROR:root:Failed to load model: Could not load the model:
/tmp/model/0001/model.pkl. Did not recognise loaded array dytpe. (Error
code: 0)

I tried with pickle and joblib but same error message.

**Comment by entrpn** [comment]
Can you share your Dockerfile so I can see where are you putting the model.pkl file?

**Comment by prashanaga** [comment]
Here is my ipnb.

**Comment by prashanaga** [comment]
Hi,
Have you got some errors?

**Comment by entrpn** [comment]
@prashanaga I cannot see your attachment.

**Comment by prashanaga** [comment]
@component(
    packages_to_install=["scikit-learn", "pandas", "joblib", "db-dtypes","xgboost","pickle5"],
    base_image="python:3.9",
    output_component_file="model_training.yaml",
)
def training_classmod(
    data1: Input[Dataset],
    metrics: Output[Metrics],
    model: Output[Model]
):
    
    from sklearn.metrics import roc_curve
    from sklearn.model_selection import train_test_split
    import sklearn.externals
    from joblib import dump
    from sklearn.metrics import confusion_matrix
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    import pandas as pd
    from sklearn.ensemble import RandomForestRegressor
    
    df_train=pd.read_csv(data1.path)
    # X = data_encoded.drop(columns=['Attrition_Flag'])
    # y = data_encoded['Attrition_Flag']
    # X_train, X_test, y_train, y_test=df_train.drop(['BERAmountforPeriod'],axis=1),df_test.drop(['BERAmountforPeriod'],axis=1),df_train['BERAmountforPeriod'],df_test['BERAmountforPeriod']
    
    X_train, y_train = df_train.drop(['BERAmountforPeriod'],axis=1),df_train['BERAmountforPeriod']

    
#     import xgboost as xgb
    
#     best_xgb_model = xgb.XGBRegressor(colsample_bytree=0.7,
#                  learning_rate=0.03,
#                  max_depth=5,
#                  min_child_weight=4,
#                  n_estimators=500,                                                                    
#                  subsample=0.7,
#                  seed=42)
    
#     best_xgb_model.fit(X_train, y_train)
    
    best_xgb_model = RandomForestRegressor(max_depth=2, random_state=0)
    best_xgb_model.fit(X_train, y_train)
    
    dump(best_xgb_model, model.path + ".joblib")
    
#     import pickle5 as pickle

#     with open(model.path + ".pkl", 'wb') as f:
#         pickle.dump(best_xgb_model, f)
    print("printing model path in class mod",model.path)




@component(
    packages_to_install=["google-cloud-aiplatform"],
    base_image="python:3.9",
    output_component_file="model_deployment.yaml",
)
def model_deployment(
    model: Input[Model],
    project: str,
    region: str,
    vertex_endpoint: Output[Artifact],
    vertex_model: Output[Model]
):
    from google.cloud import aiplatform

    aiplatform.init(project=project, location=region)
    print("*************************dir path********************",model.uri)
    print("*************************dir path********************",model.uri.replace("model", ""))

    deployed_model = aiplatform.Model.upload(
        display_name="custom-model-pipeline",
        artifact_uri = model.uri.replace("model", ""), 
        # artifact_uri= vertex_model.path+".joblib",
        serving_container_image_uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.0-24:latest"
    )
    endpoint = deployed_model.deploy(machine_type="n1-standard-4")

    # Save data to the output params
    vertex_endpoint.uri = endpoint.resource_name
    vertex_model.uri = deployed_model.resource_name



@pipeline(
    # Default pipeline root. You can override it when submitting the pipeline.
    pipeline_root=PIPELINE_ROOT,
    # A name for the pipeline.
    name="custom-pipeline",
)
def pipeline(
    bq_table_1: str = "",
   
    output_data_path: str = "data.csv",
    project: str = PROJECT_ID,
    region: str = REGION
):
    dataset_task_1 = get_data(bq_table_1)
    # dataset_task_2 = get_data_2(bq_table_2)
    data_transform=data_transformation(dataset_task_1.output)

    model_task = training_classmod(data_transform.output)

    deploy_task = model_deployment(model=model_task.outputs["model"],project=project,region=region)

**Comment by prashanaga** [comment]
`@component(
    packages_to_install=["scikit-learn", "pandas", "joblib", "db-dtypes","xgboost","pickle5"],
    base_image="python:3.9",
    output_component_file="model_training.yaml",
)
def training_classmod(
    data1: Input[Dataset],
    metrics: Output[Metrics],
    model: Output[Model]
):
    
    from sklearn.metrics import roc_curve
    from sklearn.model_selection import train_test_split
    import sklearn.externals
    from joblib import dump
    from sklearn.metrics import confusion_matrix
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    import pandas as pd
    from sklearn.ensemble import RandomForestRegressor
    
    df_train=pd.read_csv(data1.path)
    # X = data_encoded.drop(columns=['Attrition_Flag'])
    # y = data_encoded['Attrition_Flag']
    # X_train, X_test, y_train, y_test=df_train.drop(['BERAmountforPeriod'],axis=1),df_test.drop(['BERAmountforPeriod'],axis=1),df_train['BERAmountforPeriod'],df_test['BERAmountforPeriod']
    
    X_train, y_train = df_train.drop(['BERAmountforPeriod'],axis=1),df_train['BERAmountforPeriod']

    
#     import xgboost as xgb
    
#     best_xgb_model = xgb.XGBRegressor(colsample_bytree=0.7,
#                  learning_rate=0.03,
#                  max_depth=5,
#                  min_child_weight=4,
#                  n_estimators=500,                                                                    
#                  subsample=0.7,
#                  seed=42)
    
#     best_xgb_model.fit(X_train, y_train)
    
    best_xgb_model = RandomForestRegressor(max_depth=2, random_state=0)
    best_xgb_model.fit(X_train, y_train)
    
    dump(best_xgb_model, model.path + ".joblib")
    
#     import pickle5 as pickle

#     with open(model.path + ".pkl", 'wb') as f:
#         pickle.dump(best_xgb_model, f)
    print("printing model path in class mod",model.path)
`

`@component(
    packages_to_install=["google-cloud-aiplatform"],
    base_image="python:3.9",
    output_component_file="model_deployment.yaml",
)
def model_deployment(
    model: Input[Model],
    project: str,
    region: str,
    vertex_endpoint: Output[Artifact],
    vertex_model: Output[Model]
):
    from google.cloud import aiplatform

    aiplatform.init(project=project, location=region)
    print("*************************dir path********************",model.uri)
    print("*************************dir path********************",model.uri.replace("model", ""))

    deployed_model = aiplatform.Model.upload(
        display_name="custom-model-pipeline",
        artifact_uri = model.uri.replace("model", ""), 
        # artifact_uri= vertex_model.path+".joblib",
        serving_container_image_uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.0-24:latest"
    )
    endpoint = deployed_model.deploy(machine_type="n1-standard-4")

    # Save data to the output params
    vertex_endpoint.uri = endpoint.resource_name
    vertex_model.uri = deployed_model.resource_name`


`@pipeline(
    # Default pipeline root. You can override it when submitting the pipeline.
    pipeline_root=PIPELINE_ROOT,
    # A name for the pipeline.
    name="custom-pipeline",
)
def pipeline(
    bq_table_1: str = "",
   
    output_data_path: str = "data.csv",
    project: str = PROJECT_ID,
    region: str = REGION
):
    dataset_task_1 = get_data(bq_table_1)
    # dataset_task_2 = get_data_2(bq_table_2)
    data_transform=data_transformation(dataset_task_1.output)

    model_task = training_classmod(data_transform.output)

    deploy_task = model_deployment(model=model_task.outputs["model"],project=project,region=region)`

**Comment by prashanaga** [comment]
`@component(
    packages_to_install=["scikit-learn", "pandas", "joblib", "db-dtypes","xgboost","pickle5"],
    base_image="python:3.9",
    output_component_file="model_training.yaml",
)
def training_classmod(
    data1: Input[Dataset],
    metrics: Output[Metrics],
    model: Output[Model]
):
    
    from sklearn.metrics import roc_curve
    from sklearn.model_selection import train_test_split
    import sklearn.externals
    from joblib import dump
    from sklearn.metrics import confusion_matrix
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    import pandas as pd
    from sklearn.ensemble import RandomForestRegressor
    
    df_train=pd.read_csv(data1.path)
    
    X_train, y_train = df_train.drop(['BERAmountforPeriod'],axis=1),df_train['BERAmountforPeriod']


    
    best_xgb_model = RandomForestRegressor(max_depth=2, random_state=0)
    best_xgb_model.fit(X_train, y_train)
    
    dump(best_xgb_model, model.path + ".joblib")
    

    print("printing model path in class mod",model.path)
`


`@component(
    packages_to_install=["google-cloud-aiplatform"],
    base_image="python:3.9",
    output_component_file="model_deployment.yaml",
)
def model_deployment(
    model: Input[Model],
    project: str,
    region: str,
    vertex_endpoint: Output[Artifact],
    vertex_model: Output[Model]
):
    from google.cloud import aiplatform

    aiplatform.init(project=project, location=region)
    print("*************************dir path********************",model.uri)
    print("*************************dir path********************",model.uri.replace("model", ""))

    deployed_model = aiplatform.Model.upload(
        display_name="custom-model-pipeline",
        artifact_uri = model.uri.replace("model", ""), 
        # artifact_uri= vertex_model.path+".joblib",
        serving_container_image_uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.0-24:latest"
    )
    endpoint = deployed_model.deploy(machine_type="n1-standard-4")

    # Save data to the output params
    vertex_endpoint.uri = endpoint.resource_name
    vertex_model.uri = deployed_model.resource_name`




`@pipeline(
    # Default pipeline root. You can override it when submitting the pipeline.
    pipeline_root=PIPELINE_ROOT,
    # A name for the pipeline.
    name="custom-pipeline",
)
def pipeline(
    bq_table_1: str = "",
   
    output_data_path: str = "data.csv",
    project: str = PROJECT_ID,
    region: str = REGION
):
    dataset_task_1 = get_data(bq_table_1)
    # dataset_task_2 = get_data_2(bq_table_2)
    data_transform=data_transformation(dataset_task_1.output)

    model_task = training_classmod(data_transform.output)

    deploy_task = model_deployment(model=model_task.outputs["model"],project=project,region=region)`

Here are my components

**Comment by prashanaga** [comment]
@entrpn Let me know if you need some more piece of code

**Comment by entrpn** [comment]
@prashanaga Can you format your pipeline code so its more readable? Its a little hard to read, but I think its because you aren't saving the model to the AIP_MODEL_DIR which is required by the next step of the pipeline. 

See this example: https://github.com/entrpn/entrpn-kfx/blob/main/my-training-code/trainer/train.py

Then you can deploy your model using ModelDeployOp https://codelabs.developers.google.com/vertex-pipelines-intro#5

**Comment by prashanaga** [comment]
@entrpn I got the error, It was a version mismatch of sk learn in the docker image and the one I used for training

**Comment by zswf-mle** [comment]
@entrpn do you know why I can't see the logs for the endpoint? It is just empty.

**Comment by entrpn** [comment]
@zswf-mle I am not sure, its been a while since I used endpoints and I moved on to other things.
